import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const sourceDir = resolve(root, 'legacy-static');
const outputPath = resolve(root, 'src/generatedPages.js');

const pageFiles = {
  home: 'index.html',
  events: 'events.html',
  team: 'team.html',
  sponsors: 'sponsors.html'
};

function extractBetween(html, startPattern, endPattern, fallback = '') {
  const start = html.search(startPattern);
  if (start === -1) return fallback;
  const startMatch = html.slice(start).match(startPattern);
  if (!startMatch) return fallback;
  const contentStart = start + startMatch[0].length;
  const end = html.slice(contentStart).search(endPattern);
  if (end === -1) return fallback;
  return html.slice(contentStart, contentStart + end);
}

function normalizeMarkup(markup) {
  return markup
    .replaceAll('href="index.html"', 'href="/"')
    .replaceAll('href="events.html"', 'href="/events"')
    .replaceAll('href="team.html"', 'href="/team"')
    .replaceAll('href="sponsors.html"', 'href="/sponsors"')
    .replaceAll("href='index.html'", "href='/'")
    .replaceAll("href='events.html'", "href='/events'")
    .replaceAll("href='team.html'", "href='/team'")
    .replaceAll("href='sponsors.html'", "href='/sponsors'");
}

function parsePage(key, filename) {
  const html = readFileSync(resolve(sourceDir, filename), 'utf8');
  const title = extractBetween(html, /<title>/i, /<\/title>/i, 'WiCS @ ASU').trim();
  const style = extractBetween(html, /<style>/i, /<\/style>/i);
  const bodyTag = html.match(/<body([^>]*)>/i);
  const bodyClass = bodyTag?.[1].match(/class=["']([^"']+)["']/i)?.[1] || '';
  const rawBody = extractBetween(html, /<body[^>]*>/i, /<\/body>/i);
  const scriptMatches = [...rawBody.matchAll(/<script[^>]*>([\s\S]*?)<\/script>/gi)];
  const script = scriptMatches.map((match) => match[1]).join('\n');
  const body = normalizeMarkup(rawBody.replace(/<script[^>]*>[\s\S]*?<\/script>/gi, '').trim());

  return { key, title, bodyClass, style, body, script };
}

const pages = Object.fromEntries(
  Object.entries(pageFiles).map(([key, filename]) => [key, parsePage(key, filename)])
);

mkdirSync(dirname(outputPath), { recursive: true });
writeFileSync(
  outputPath,
  `// Generated by scripts/generate-pages.mjs. Do not edit by hand.\n/* eslint-disable */\nexport const pages = ${JSON.stringify(pages, null, 2)};\n`
);
